

export const PROGRAMMING_LANGUAGES: string[] = [
  'Bash',
  'C',
  'C++',
  'C#',
  'CSS',
  'Dart',
  'Go',
  'HTML',
  'Java',
  'JavaScript',
  'JSON',
  'Kotlin',
  'Markdown',
  'PHP',
  'Python',
  'Ruby',
  'Rust',
  'SQL',
  'Swift',
  'TypeScript',
  'XML',
  'YAML',
].sort();

export const LANGUAGE_EXTENSIONS: { [key: string]: string } = {
  'sh': 'Bash',
  'bash': 'Bash',
  'c': 'C',
  'h': 'C',
  'cpp': 'C++',
  'hpp': 'C++',
  'cc': 'C++',
  'hh': 'C++',
  'cxx': 'C++',
  'hxx': 'C++',
  'cs': 'C#',
  'css': 'CSS',
  'dart': 'Dart',
  'go': 'Go',
  'html': 'HTML',
  'htm': 'HTML',
  'java': 'Java',
  'js': 'JavaScript',
  'jsx': 'JavaScript',
  'mjs': 'JavaScript',
  'cjs': 'JavaScript',
  'json': 'JSON',
  'kt': 'Kotlin',
  'kts': 'Kotlin',
  'md': 'Markdown',
  'php': 'PHP',
  'py': 'Python',
  'pyw': 'Python',
  'rb': 'Ruby',
  'rs': 'Rust',
  'sql': 'SQL',
  'swift': 'Swift',
  'ts': 'TypeScript',
  'tsx': 'TypeScript',
  'xml': 'XML',
  'yaml': 'YAML',
  'yml': 'YAML',
};

export const IGNORED_FILES_AND_DIRS: string[] = [
  '.git',
  '.github',
  '.vscode',
  'node_modules',
  'dist',
  'build',
  'coverage',
  '.DS_Store',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lockb',
];
